### ISSUE TITLE
Add documentation on how to build the docs in the README's Contributing section

### ISSUE THREAD

**Issue by LLCampos** [disneystreaming/weaver-test#288]
There's a `README.md` in `website/`, but doing what it is written there:

```
$ yarn
(...) 
$ yarn start
```

doesn't work, leading to the following error:

```
Error: You have 'doc' in your headerLinks, but no 'modules/docs/target/jvm-2.13/mdoc' folder exists one level up from 'website' folder. Did you run `docusaurus-init` or `npm run examples`? If so, make sure you rename 'docs-examples-from-docusaurus' to 'docs'.
    at forEach (/home/lcampos/Development/weaver-test/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:253:15)
    at Array.forEach (<anonymous>)
    at HeaderNav.renderResponsiveNav (/home/lcampos/Development/weaver-test/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:248:17)
    at HeaderNav.render (/home/lcampos/Development/weaver-test/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:325:19)
    at processChild (/home/lcampos/Development/weaver-test/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/home/lcampos/Development/weaver-test/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/home/lcampos/Development/weaver-test/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/home/lcampos/Development/weaver-test/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToStaticMarkup (/home/lcampos/Development/weaver-test/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
    at renderToStaticMarkupWithDoctype (/home/lcampos/Development/weaver-test/website/node_modules/docusaurus/lib/server/renderUtils.js:16:48)
```

**Comment by Baccata** [comment]
Good point. In the meantime, the website is created via sbt. See https://scalameta.org/mdoc/docs/docusaurus.html#create-static-site

**Comment by LLCampos** [comment]
Ah, cool! I'll create a PR adding it do the docs, then.

**Comment by LLCampos** [comment]
Cross that, not clear to me what to do after `docs/docusaurusCreateSite` -  accessing `build/index.html` redirects to `build/docs/index.html`, which doesn't exist.

**Comment by keynmol** [comment]
1. `sbt docs/docusaurusCreateSite`
2. `cd website`
3. `yarn start`

This is my usual workflow. 

And when I'm only changing `.md` files, I keep `sbt '~docs/mdoc'` 

Note that the site will look a tiny bit different because to build a versioned website we have some machinery in the script running on CI - but you don't have to worry about that.
