### ISSUE TITLE
Incorrect error message in IDEA

### ISSUE THREAD

**Issue by DenisNovac** [disneystreaming/weaver-test#504]
Weaver version: "0.7.7"

```scala
import weaver.SimpleIOSuite

class Suit extends SimpleIOSuite {

  test("init") { _ =>
    IO.pure(expect(true))
  }
}
```

This test when runs in IDEA gives this error:

```
java.lang.Exception: Could not find a suitable constructor that takes GlobalResourceF.Read
at weaver.internals.Reflection$.loadRunnableSuite(Reflection.scala:34)
	at weaver.junit.WeaverRunner.suite$lzycompute(WeaverRunner.scala:18)
	at weaver.junit.WeaverRunner.suite(WeaverRunner.scala:17)
	at weaver.junit.WeaverRunner.testDescriptions$lzycompute(WeaverRunner.scala:22)
	at weaver.junit.WeaverRunner.testDescriptions(WeaverRunner.scala:21)
	at weaver.junit.WeaverRunner.getDescription(WeaverRunner.scala:28)
	at org.junit.runners.model.RunnerBuilder.configureRunner(RunnerBuilder.java:81)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:72)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

But in SBT it gives this error:

```
[error] - Unexpected failure 0ms
[error]   Reflection$$anon$3: class com.github.denisnovac.multitest.jdbc.Suit is a class. It should either be an object, or have a constructor that takes a single parameter of type weaver.GlobalResourceF$Read
```

Which is far more informative. So the solution is to make `Suit` an `object` (i didn't read the docs carefully enough and got this).
I understand this is not a weaver problem but i want to report this for anyone who will try to search an error message.

**Comment by martinprobson** [comment]
@DenisNovac Thank you for this, that IntelliJ message was confusing me :+1:
