### ISSUE TITLE
frequent ClosedChannelException 

### ISSUE THREAD

**Issue by i10416** [disneystreaming/weaver-test#668]
I almost always encounter this error on ubuntu 20.04 though I have yet to find the root cause of this exception.

In my tests, I use http4s 0.23.19 and cats effect 3.5.0 to communicate with API.

http client is shared between tests using sharedResource 
field in `IOSuite`.

```
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.begin(AsynchronousSocketChannelImpl.java:119)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.shutdownInput(AsynchronousSocketChannelImpl.java:536)
	at fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk$$anonfun$1$$anonfun$1$$anonfun$1(SocketPlatform.scala:121)
	at fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk$$anonfun$1$$anonfun$1$$anonfun$adapted$1(SocketPlatform.scala:123)
	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk$$anonfun$1$$anonfun$1(SocketPlatform.scala:123)
	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk$$anonfun$1(SocketPlatform.scala:123)
	at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:123)
	at flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.read$$anonfun$1(SocketPlatform.scala:84)
	at delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.withReadBuffer(SocketPlatform.scala:58)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
```

**Comment by i10416** [comment]
It is used in private repo for work, so I can't share a repo. However, I will prepare minimal reproduction in this weekends.

**Comment by daddykotex** [comment]
I can share the circumstances in which I have seen these issues. We are running benchmarks on a http4s application. If the application is long lived and it goes through multiple pass of load testing, we're guaranteed to see it show up.

Basically, the application is a server that interacts with another server over http. So it has ember HTTP client to do so. When the load begins, I assume the application starts to send out request to the upstream server. Over time more and more requests are sent and the connection pool grows accordingly. At some point, we stop the load test, and the client connections start to _expire_ (I guess it's that the idle connection timeout is reached) and the connection are closed.

I'm assuming something in the process is not invoked in the right order, or some resources is left open so we see the stack. I can probable put something together in a few mins, let me give it a shot.

**Comment by armanbilge** [comment]
Thanks! I think I already figured out the problem in https://github.com/typelevel/fs2/commit/0a912a2298efd564ba85b78daaf1ffaa0f82d6c1, going to put up a PR shortly.

If you've got a reliable reproducer, I can publish you a snapshot to test it with?

**Comment by armanbilge** [comment]
I published `fs2-io` version `3.7.0-52-0a912a2-SNAPSHOT` to `https://s01.oss.sonatype.org/content/repositories/snapshots/`

**Comment by daddykotex** [comment]
Ok, the repro works

Let me give that a shot

**Comment by daddykotex** [comment]
it works, you can test it yourself here: https://github.com/daddykotex/scala-scripts/commit/35454ed9079f7eb125eeaa9619a3c977ad1c366d

**Comment by i10416** [comment]
Sorry for my late response. I also confirmed that tests don't show ClosedChannelException with fs2-io 3.7.0-52-0a912a2-SNAPSHOT. Thank you.
